[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# foundry.toml
 
solc_version = '0.8.26'
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true

# Ignore linting warnings
[lint]
lint_on_build = true

# Gas reporting
[profile.gas_report]
enabled = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
